package com.kuaforrys.kuafor_backend.repository;

import com.kuaforrys.kuafor_backend.entity.Hizmet;
import org.springframework.data.jpa.repository.JpaRepository;

public interface HizmetRepository extends JpaRepository<Hizmet, Long> {
}